
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'HCPlayerTest' do

pod 'HCMinizip'
pod 'hccoren’,’~>0.3.3’
pod 'HCBaseSystem’,’~>0.3.3’
pod 'HCMVManager','~>0.9.9'
pod 'HCAudioUnit','~>0.2.1'

end
