
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'HCPlayerTest' do

pod 'HCMinizip'
pod 'hccoren’,’~>0.2.0’
pod 'HCBaseSystem’,’~>0.2.4’
pod 'HCMVManager','~>0.1.0'
pod 'HCAudioUnit','~>0.1.8'

end
